image: registry.staging.qweib.com/qweib/maven-dind:3.6.0-jdk-8

stages:
  - deploy

build:
  stage: deploy
  script: mvn -D skipTests clean source:jar deploy
  tags:
   - maven
   - deploy
  only:
   - dev
   - future01
